[package]
name = "omp-core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
samp-query = { git = "https://github.com/TanF12/samp-query" }
reqwest = { version = "0.13.4", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"